"""Tests for housekeeping.py. Run: cd automations && python3 -m unittest test_housekeeping

Every behavioural test is written once as a mixin over fixture TEMPLATES and executed for both
built-in label sets (classes suffixed En / Pl are generated by @for_each_label_set).
"""
import contextlib
import io
import json
import shutil
import tempfile
import unittest
from datetime import date
from pathlib import Path

import housekeeping as hk

REPO_ROOT = Path(__file__).resolve().parent.parent


def tokens(lb):
    f = lb.fields
    return {
        "ST": f["status"], "OWNER": f["owner"], "TOPIC": f["topic"], "LINEAR": f["linear"],
        "DEADLINE": f["deadline"], "CREATED": f["created"], "UPDATED": f["updated"],
        "NONE": lb.none, "OPEN": lb.statuses["open"], "CLOSED": lb.statuses["closed"],
        "OBSOLETE": lb.statuses["obsolete"], "STATE": lb.state_line, "NEXT": lb.next_step_line,
        "SEC_OPEN": lb.sections["open"], "SEC_REC": lb.sections["recurring"], "SEC_CAND": lb.sections["candidates"],
        "CAND": lb.candidate_type, "CARD_STATE": lb.card_state_heading, "CARD_HIST": lb.card_history_heading,
        "FOOTER": lb.history_footer, "SRC": lb.source_marker,
        "EV_CREATED": lb.events["created"], "EV_TYPE": lb.events["type"], "EV_OBSOLETE": lb.events["obsolete"],
    }


TASKS_TPL = """# TASKS — register
_intro_

## {SEC_OPEN}

### T-20260929-03 · ACTION_REQUIRED · Vendor X: send signed contract
- {ST}: {OPEN} · {OWNER}: Alex [TEAM] · {TOPIC}: [[example-topic]] · {LINEAR}: {NONE} · {DEADLINE}: {NONE} · {CREATED}: 2026-09-29 · {UPDATED}: 2026-09-30
- {STATE}: draft sent, waiting for the signature date. ({SRC}: Chat C1/p1, 2026-09-28)
- {NEXT}: forward the date to finance.

### T-20260922-01 · WAITING_FOR_OTHER · Partner Y: comments on 5 documents
- {ST}: {OPEN} · {OWNER}: Alex [OPS] · {TOPIC}: [[other-topic]] · {LINEAR}: ABC-4167 · {DEADLINE}: 2026-10-03 · {CREATED}: 2026-09-22 · {UPDATED}: 2026-09-29
- {STATE}: returned, waiting for Sam. ({SRC}: Mail 1a0e, 2026-09-28)

## {SEC_REC}
- every Monday: review records without a ticket

## {SEC_CAND}

### T-20260930-01 · {CAND} · Customer Z: technical set-up
- {ST}: {OPEN} · {OWNER}: Alex [TEAM] · {TOPIC}: [[example-topic]] · {LINEAR}: {NONE} · {DEADLINE}: {NONE} · {CREATED}: 2026-09-30 · {UPDATED}: 2026-09-30
- {STATE}: Kim mentioned "potential help". ({SRC}: Chat C049/t1790702478, 2026-09-29)
"""

CARD_TPL = """---
topic: Example topic
aliases: [example-topic]
related_topics: [other-topic, third-topic]
watch: true
---
# Example topic

## Summary
One sentence.

## {CARD_STATE}
- Rollout plan: schedule in review (2026-09-25) → T-20260924-02

## People
- Jordan Doe [CLIENT!] — Customer Z

{FOOTER}: [[example-topic-history]] · archives: [[example-topic-history-2026-Q3]]
"""

HIST_TPL = """---
part_of: example-topic
period: 2026-Q4
previous: [example-topic-history-2026-Q3]
---
- 2026-10-01: Customer Z sent schedules 2A/2B. ({SRC}: Mail 1a0c, 2026-10-01) [confidence: high] [T-20260924-02]
- 2026-10-02: technical meeting held. ({SRC}: Calendar, 2026-10-02)
"""

LOG_TPL = """---
period: 2026-Q4
previous: [archive/tasks/TASKS-log-2026-Q3]
---
- 2026-10-01 07:40 · T-20260924-02 · {EV_CREATED} · from Mail 1a0c, topic [[example-topic]]
- 2026-10-02 09:12 · T-20260924-02 · {EV_TYPE} ACTION_REQUIRED→WAITING_FOR_OTHER · waiting for Customer Z ({SRC}: Mail 1a0d)
"""


def for_each_label_set(mixin):
    """Generate <Mixin>En and <Mixin>Pl TestCase classes running the mixin for each built-in label set."""
    for suffix, lb in (("En", hk.EN), ("Pl", hk.PL)):
        name = f"{mixin.__name__}{suffix}"
        globals()[name] = type(name, (mixin, unittest.TestCase), {"LABELS": lb})
    return mixin


class Base:
    LABELS = hk.EN

    def L(self, s):
        return s.format(**tokens(self.LABELS))

    @property
    def GOOD(self):
        return self.L(TASKS_TPL)

    @property
    def CARD_GOOD(self):
        return self.L(CARD_TPL)

    @property
    def HIST_GOOD(self):
        return self.L(HIST_TPL)

    @property
    def LOG_GOOD(self):
        return self.L(LOG_TPL)

    def parse(self, text):
        return hk.parse_tasks(text, labels=self.LABELS)

    def check(self, text, today=date(2026, 9, 30)):
        recs, _ = self.parse(text)
        return [v.code for v in hk.check_tasks(recs, today, labels=self.LABELS)]

    def make_vault(self, tasks=None, log=None, hist=None):
        root = build_vault(self.LABELS, tasks, log, hist)
        self.addCleanup(shutil.rmtree, root, True)
        return root


def build_vault(lb, tasks=None, log=None, hist=None):
    """Temporary vault with TASKS.md, TASKS-log.md, one card and its history rendered in label set `lb`."""
    render = lambda s: s.format(**tokens(lb))
    root = Path(tempfile.mkdtemp())
    (root / "archive" / "tasks").mkdir(parents=True)
    (root / "topics" / "domains" / "example").mkdir(parents=True)
    (root / "TASKS.md").write_text(tasks if tasks is not None else render(TASKS_TPL), encoding="utf-8")
    (root / "TASKS-log.md").write_text(log if log is not None else render(LOG_TPL), encoding="utf-8")
    (root / "topics/domains/example/example-topic.md").write_text(render(CARD_TPL), encoding="utf-8")
    (root / "topics/domains/example/example-topic-history.md").write_text(
        hist if hist is not None else render(HIST_TPL), encoding="utf-8")
    return root


@for_each_label_set
class ParseTasks(Base):
    def test_parses_three_records_without_violations(self):
        recs, viol = self.parse(self.GOOD)
        self.assertEqual(viol, [])
        self.assertEqual([r.id for r in recs], ["T-20260929-03", "T-20260922-01", "T-20260930-01"])
        r = recs[0]
        lb = self.LABELS
        self.assertEqual((r.typ, r.status, r.linear, r.deadline), ("ACTION_REQUIRED", lb.statuses["open"], lb.none, lb.none))
        self.assertEqual(r.topic, "example-topic")
        self.assertEqual(r.next_step, "forward the date to finance.")
        self.assertEqual(r.section, lb.sections["open"])
        self.assertEqual(recs[2].section, lb.sections["candidates"])

    def test_header_without_id_is_violation(self):
        bad = self.GOOD.replace("### T-20260922-01 · WAITING_FOR_OTHER · ", "### [ACTION_REQUIRED — NEW 2026-09-22] ")
        _, viol = self.parse(bad)
        self.assertEqual([v.code for v in viol], ["HEADER_FORMAT"])

    def test_wrong_field_order_is_violation(self):
        bad = self.GOOD.replace(self.L("- {ST}: {OPEN} · {OWNER}: Alex [TEAM] · {TOPIC}: [[example-topic]] · {LINEAR}: {NONE} · {DEADLINE}: {NONE} · {CREATED}: 2026-09-29"),
                                self.L("- {OWNER}: Alex [TEAM] · {ST}: {OPEN} · {TOPIC}: [[example-topic]] · {LINEAR}: {NONE} · {DEADLINE}: {NONE} · {CREATED}: 2026-09-29"))
        _, viol = self.parse(bad)
        self.assertIn("FIELDS_FORMAT", [v.code for v in viol])

    def test_extra_line_in_record_is_violation(self):
        nxt = self.L("- {NEXT}: forward the date to finance.\n")
        bad = self.GOOD.replace(nxt, nxt + "> **REVIEW 2026-09-30:** long comment\n")
        _, viol = self.parse(bad)
        self.assertIn("EXTRA_LINE", [v.code for v in viol])

    def test_stan_without_source_is_violation(self):
        bad = self.GOOD.replace(self.L("- {STATE}: returned, waiting for Sam. ({SRC}: Mail 1a0e, 2026-09-28)"),
                                self.L("- {STATE}: returned, waiting for Sam."))
        _, viol = self.parse(bad)
        self.assertIn("STAN_NO_SOURCE", [v.code for v in viol])


@for_each_label_set
class CheckTasks(Base):
    def test_clean_file_has_no_violations(self):
        self.assertEqual(self.check(self.GOOD), [])

    def test_duplicate_id(self):
        self.assertIn("DUPLICATE_ID", self.check(self.GOOD.replace("T-20260922-01", "T-20260929-03")))

    def test_closed_status_in_tasks_md(self):
        bad = self.GOOD.replace(self.L("- {ST}: {OPEN} · {OWNER}: Alex [OPS]"), self.L("- {ST}: {CLOSED} · {OWNER}: Alex [OPS]"))
        self.assertIn("STATUS_NOT_OPEN", self.check(bad))

    def test_stale_candidate_over_14_days(self):
        self.assertIn("CANDIDATE_STALE", self.check(self.GOOD, date(2026, 10, 15)))

    def test_records_not_sorted_by_id_desc(self):
        swapped = self.GOOD.replace("### T-20260929-03", "### T-20260901-03").replace(
            self.L("{CREATED}: 2026-09-29"), self.L("{CREATED}: 2026-09-01"))
        self.assertIn("ORDER", self.check(swapped))


@for_each_label_set
class Quarter(Base):
    def test_quarter_of(self):
        self.assertEqual(hk.quarter_of(date(2026, 9, 30)), "2026-Q3")
        self.assertEqual(hk.quarter_of(date(2026, 10, 1)), "2026-Q4")


@for_each_label_set
class FrontMatter(Base):
    def test_parses_scalars_and_lists(self):
        fm, n = hk.parse_front_matter(self.HIST_GOOD)
        self.assertEqual(fm["part_of"], "example-topic")
        self.assertEqual(fm["previous"], ["example-topic-history-2026-Q3"])
        self.assertEqual(n, 5)

    def test_no_front_matter(self):
        self.assertEqual(hk.parse_front_matter("# title\n"), ({}, 0))


@for_each_label_set
class CheckCard(Base):
    def codes(self, text, name="c.md"):
        return [v.code for v in hk.check_card(text, name, labels=self.LABELS)]

    def test_good_card(self):
        self.assertEqual(hk.check_card(self.CARD_GOOD, "topics/domains/example/example-topic.md", labels=self.LABELS), [])

    def test_history_section_in_card(self):
        bad = self.CARD_GOOD.replace("## People", self.L("## {CARD_HIST} (newest on top)\n- 2026-09-01: x\n\n## People"))
        self.assertIn("CARD_HAS_HISTORY", self.codes(bad))

    def test_missing_state_section(self):
        bad = self.CARD_GOOD.replace(self.L("## {CARD_STATE}"), "## State-ish")
        self.assertIn("CARD_NO_STATE", self.codes(bad))

    def test_history_in_related_topics(self):
        bad = self.CARD_GOOD.replace("related_topics: [other-topic, third-topic]", "related_topics: [other-topic, other-topic-history]")
        self.assertIn("RELATED_HISTORY", self.codes(bad))


@for_each_label_set
class CheckHistory(Base):
    KNOWN = {"T-20260924-02"}

    def codes(self, text, name="x-history.md", known=None, today=date(2026, 10, 5)):
        return [v.code for v in hk.check_history(text, name, self.KNOWN if known is None else known, today, labels=self.LABELS)]

    def test_good_history(self):
        self.assertEqual(self.codes(self.HIST_GOOD), [])

    def test_out_of_order(self):
        self.assertIn("HIST_ORDER", self.codes(self.HIST_GOOD.replace("- 2026-10-02:", "- 2026-09-02:")))

    def test_rollover_due_for_live_file(self):
        self.assertIn("ROLLOVER_DUE", self.codes(self.HIST_GOOD, today=date(2027, 1, 2)))

    def test_archived_file_not_rollover_checked(self):
        self.assertEqual(self.codes(self.HIST_GOOD, name="x-history-2026-Q4.md", today=date(2027, 1, 2)), [])

    def test_archived_file_accepts_legacy_lines(self):
        legacy = self.HIST_GOOD.replace("- 2026-10-02: technical", "- 2026-05: month-only entry from an old card\n"
                                        "- **2026-09-15 (call):** bold entry\n- 2026-10-02: technical")
        self.assertEqual(self.codes(legacy, name="x-history-2026-Q3.md"), [])
        self.assertIn("HIST_LINE_FORMAT", self.codes(legacy))

    def test_unknown_task_id(self):
        self.assertIn("UNKNOWN_TASK_ID", self.codes(self.HIST_GOOD, known=set()))

    def test_bad_line(self):
        self.assertIn("HIST_LINE_FORMAT", self.codes(self.HIST_GOOD + "> comment without a date\n"))


@for_each_label_set
class CheckLog(Base):
    KNOWN = {"T-20260924-02"}

    def codes(self, text, today=date(2026, 10, 5)):
        return [v.code for v in hk.check_log(text, "TASKS-log.md", self.KNOWN, today, labels=self.LABELS)]

    def test_good_log(self):
        self.assertEqual(self.codes(self.LOG_GOOD), [])

    def test_order_by_datetime(self):
        self.assertIn("LOG_ORDER", self.codes(self.LOG_GOOD.replace("- 2026-10-02 09:12", "- 2026-10-01 07:39")))

    def test_line_format(self):
        self.assertIn("LOG_LINE_FORMAT", self.codes(self.LOG_GOOD + "- 2026-10-03 · T-20260924-02 · no time\n"))

    def test_rollover_due(self):
        self.assertIn("ROLLOVER_DUE", self.codes(self.LOG_GOOD, today=date(2027, 1, 2)))


@for_each_label_set
class NewId(Base):
    def test_first_id_of_day(self):
        root = self.make_vault()
        self.assertEqual(hk.new_id(root, date(2026, 10, 7)), "T-20261007-01")

    def test_next_id_same_day_counts_archive_too(self):
        root = self.make_vault()
        (root / "archive/tasks/TASKS-2026-Q4.md").write_text("### T-20260930-02 · FYI · x\n", encoding="utf-8")
        self.assertEqual(hk.new_id(root, date(2026, 9, 30)), "T-20260930-03")


@for_each_label_set
class Apply(Base):
    def test_rollover_moves_log_and_history(self):
        root = self.make_vault()
        ops = hk.apply(root, date(2027, 1, 2), labels=self.LABELS)
        hist = root / "topics/domains/example"
        self.assertTrue((root / "archive/tasks/TASKS-log-2026-Q4.md").exists())
        self.assertTrue((hist / "example-topic-history-2026-Q4.md").exists())
        live_log, _ = hk.parse_front_matter((root / "TASKS-log.md").read_text(encoding="utf-8"))
        live_hist, _ = hk.parse_front_matter((hist / "example-topic-history.md").read_text(encoding="utf-8"))
        self.assertEqual(live_log["period"], "2027-Q1")
        self.assertEqual(live_hist["previous"], ["example-topic-history-2026-Q3", "example-topic-history-2026-Q4"])
        self.assertTrue(any("rollover" in o for o in ops))

    def test_archives_closed_record_and_keeps_open(self):
        closed = self.GOOD.replace(self.L("- {ST}: {OPEN} · {OWNER}: Alex [OPS]"), self.L("- {ST}: {CLOSED} · {OWNER}: Alex [OPS]"))
        root = self.make_vault(tasks=closed)
        hk.apply(root, date(2026, 10, 5), labels=self.LABELS)
        tasks = (root / "TASKS.md").read_text(encoding="utf-8")
        arch = (root / "archive/tasks/TASKS-2026-Q4.md").read_text(encoding="utf-8")
        self.assertNotIn("T-20260922-01", tasks)
        self.assertIn("### T-20260922-01 · WAITING_FOR_OTHER", arch)
        self.assertIn(self.L("- {ST}: {CLOSED}"), arch)
        self.assertIn("T-20260929-03", tasks)
        recs, viol = self.parse(tasks)
        self.assertEqual(viol, [])
        self.assertEqual(len(recs), 2)

    def test_expires_stale_candidate_with_log_line(self):
        root = self.make_vault()
        hk.apply(root, date(2026, 10, 20), labels=self.LABELS)
        tasks = (root / "TASKS.md").read_text(encoding="utf-8")
        log = (root / "TASKS-log.md").read_text(encoding="utf-8")
        arch = (root / "archive/tasks/TASKS-2026-Q4.md").read_text(encoding="utf-8")
        self.assertNotIn("T-20260930-01", tasks)
        self.assertIn(self.L("- {ST}: {OBSOLETE} · {OWNER}: Alex [TEAM]"), arch)
        reason = self.LABELS.msg("expire_reason", days=14)
        self.assertIn(self.L("· T-20260930-01 · {EV_OBSOLETE}: ") + reason, log)

    def test_apply_is_idempotent(self):
        root = self.make_vault()
        hk.apply(root, date(2026, 10, 20), labels=self.LABELS)
        self.assertEqual(hk.apply(root, date(2026, 10, 20), labels=self.LABELS), [])


# ---------------------------------------------------------------------------
# Label sets: exact formats, selection, overrides, errors
# ---------------------------------------------------------------------------

PL_LITERAL = """## Otwarte

### T-20260929-03 · ACTION_REQUIRED · Dostawca X: wysłać podpisaną umowę
- Status: otwarte · Owner: Alex [TEAM] · Temat: [[example-topic]] · Linear: brak · Deadline: brak · Utworzono: 2026-09-29 · Aktualizacja: 2026-09-30
- Stan: projekt wysłany, czekam na termin podpisu. (źródło: Chat C1/p1, 2026-09-28)
- Następny krok: przekazać termin finansom.

## Cykliczne
- co poniedziałek: przegląd

## Potencjalne zadania

### T-20260930-01 · POTENCJALNE · Klient Z: set-up techniczny
- Status: otwarte · Owner: Alex [TEAM] · Temat: brak · Linear: ABC-12 · Deadline: 2026-10-10 · Utworzono: 2026-09-30 · Aktualizacja: 2026-09-30
- Stan: wzmianka o pomocy. (źródło: Chat C2/t1, 2026-09-29)
"""

EN_LITERAL = """## Open

### T-20260101-01 · ACTION_REQUIRED · Vendor X: send signed contract
- Status: open · Owner: Alex [TEAM] · Topic: [[example-topic]] · Linear: none · Deadline: 2026-01-15 · Created: 2026-01-01 · Updated: 2026-01-02
- State: draft sent, waiting for the signature date. (source: Chat C1/p1, 2026-01-01)
- Next step: forward the date to finance.

## Recurring
- every Monday: review

## Candidates

### T-20260102-01 · CANDIDATE · Customer Z: technical set-up
- Status: open · Owner: Alex [TEAM] · Topic: none · Linear: ABC-12 · Deadline: none · Created: 2026-01-02 · Updated: 2026-01-02
- State: help mentioned. (source: Chat C2/t1, 2026-01-02)
"""


class ExactFormats(unittest.TestCase):
    def test_pl_label_set_reads_the_polish_vault_format(self):
        recs, viol = hk.parse_tasks(PL_LITERAL, labels=hk.PL)
        self.assertEqual(viol, [])
        self.assertEqual([r.section for r in recs], ["Otwarte", "Potencjalne zadania"])
        self.assertEqual(recs[1].topic, "brak")
        self.assertEqual(hk.check_tasks(recs, date(2026, 10, 1), labels=hk.PL), [])

    def test_en_label_set_reads_the_english_format(self):
        recs, viol = hk.parse_tasks(EN_LITERAL, labels=hk.EN)
        self.assertEqual(viol, [])
        self.assertEqual([r.section for r in recs], ["Open", "Candidates"])
        self.assertEqual(hk.check_tasks(recs, date(2026, 1, 3), labels=hk.EN), [])

    def test_label_sets_do_not_cross_parse(self):
        _, viol = hk.parse_tasks(EN_LITERAL.replace("## Open", "## Otwarte").replace("## Candidates", "## Potencjalne zadania"), labels=hk.PL)
        self.assertIn("FIELDS_FORMAT", [v.code for v in viol])
        recs, _ = hk.parse_tasks(PL_LITERAL, labels=hk.EN)
        self.assertEqual(recs, [])  # Polish section names are not record sections in the en set

    def test_messages_are_localised(self):
        _, viol_en = hk.parse_tasks(EN_LITERAL.replace(" (source: Chat C1/p1, 2026-01-01)", ""), labels=hk.EN)
        _, viol_pl = hk.parse_tasks(PL_LITERAL.replace(" (źródło: Chat C1/p1, 2026-09-28)", ""), labels=hk.PL)
        self.assertEqual(viol_en[0].message, "T-20260101-01: State without (source: …)")
        self.assertEqual(viol_pl[0].message, "T-20260929-03: Stan bez (źródło: …)")


class LabelSelection(unittest.TestCase):
    def vault(self, labels_json=None):
        root = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, root, True)
        (root / "automations").mkdir()
        if labels_json is not None:
            (root / "automations" / "housekeeping.labels.json").write_text(json.dumps(labels_json), encoding="utf-8")
        return root

    def run_main(self, argv):
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = hk.main(argv)
        return code, out.getvalue(), err.getvalue()

    def test_default_is_en(self):
        self.assertEqual(hk.resolve_labels(None, self.vault()).fields["created"], "Created")

    def test_vault_file_selects_base(self):
        self.assertEqual(hk.resolve_labels(None, self.vault({"base": "pl"})).fields["created"], "Utworzono")

    def test_vault_file_without_base_defaults_to_en(self):
        lb = hk.resolve_labels(None, self.vault({"none": "n/a"}))
        self.assertEqual((lb.none, lb.fields["topic"]), ("n/a", "Topic"))

    def test_cli_overrides_vault_file(self):
        self.assertEqual(hk.resolve_labels("en", self.vault({"base": "pl"})).state_line, "State")
        self.assertEqual(hk.resolve_labels("pl", self.vault()).state_line, "Stan")

    def test_cli_path_to_json(self):
        root = self.vault()
        p = root / "my-labels.json"
        p.write_text(json.dumps({"base": "pl", "state_line": "Status bieżący"}), encoding="utf-8")
        lb = hk.resolve_labels(str(p), root)
        self.assertEqual((lb.state_line, lb.fields["topic"]), ("Status bieżący", "Temat"))

    def test_overrides_merge_nested_keys(self):
        lb = hk.resolve_labels(None, self.vault({"base": "en", "fields": {"linear": "Jira"},
                                                 "sections": {"candidates": "Potential tasks"},
                                                 "_comment": "ignored"}))
        self.assertEqual((lb.fields["linear"], lb.fields["status"]), ("Jira", "Status"))
        text = EN_LITERAL.replace("Linear:", "Jira:").replace("## Candidates", "## Potential tasks")
        recs, viol = hk.parse_tasks(text, labels=lb)
        self.assertEqual(viol, [])
        self.assertEqual(recs[1].section, "Potential tasks")

    def test_unknown_label_set_is_clear_error(self):
        with self.assertRaises(hk.LabelError) as cm:
            hk.resolve_labels("de", self.vault())
        self.assertIn("unknown label set 'de'", str(cm.exception))
        self.assertIn("en, pl", str(cm.exception))

    def test_missing_json_file_is_error(self):
        with self.assertRaises(hk.LabelError) as cm:
            hk.load_labels("/nonexistent/labels.json")
        self.assertIn("not found", str(cm.exception))

    def test_unknown_key_unknown_subkey_unknown_base_bad_json(self):
        for bad in ({"colour": "x"}, {"fields": {"prio": "P"}}, {"base": "fr"}, {"types": "FYI"}):
            with self.subTest(bad=bad), self.assertRaises(hk.LabelError):
                hk.resolve_labels(None, self.vault(bad))
        root = self.vault()
        (root / "automations" / "housekeeping.labels.json").write_text("{not json", encoding="utf-8")
        with self.assertRaises(hk.LabelError) as cm:
            hk.resolve_labels(None, root)
        self.assertIn("not valid JSON", str(cm.exception))

    def test_main_reports_label_error_with_exit_2(self):
        code, _, err = self.run_main(["--check", "--vault", str(self.vault()), "--labels", "xx"])
        self.assertEqual(code, 2)
        self.assertIn("unknown label set 'xx'", err)

    def test_main_check_uses_vault_label_file(self):
        root = build_vault(hk.PL)
        self.addCleanup(shutil.rmtree, root, True)
        (root / "automations").mkdir()
        (root / "automations" / "housekeeping.labels.json").write_text('{"base": "pl"}', encoding="utf-8")
        (root / "archive/tasks/TASKS-2026-Q3.md").write_text("### T-20260924-02 · FYI · x\n", encoding="utf-8")
        code, out, _ = self.run_main(["--check", "--vault", str(root), "--today", "2026-10-05"])
        self.assertEqual(code, 0, out)
        self.assertIn("housekeeping --check: 0 naruszeń", out)

    def test_example_label_file_is_valid(self):
        lb = hk.load_labels(str(REPO_ROOT / "automations" / "housekeeping.labels.example.json"))
        self.assertIsInstance(lb, hk.Labels)


class TemplateVault(unittest.TestCase):
    def test_shipped_template_passes_check(self):
        """The empty template in this repo must pass --check in the quarter set in TASKS-log.md."""
        fm, _ = hk.parse_front_matter((REPO_ROOT / "TASKS-log.md").read_text(encoding="utf-8"))
        year, q = str(fm["period"]).split("-Q")
        today = date(int(year), 3 * int(q), 1)
        viol = hk.run_check(REPO_ROOT, today, labels=hk.resolve_labels(None, REPO_ROOT))
        self.assertEqual([str(v) for v in viol], [])


if __name__ == "__main__":
    unittest.main()
